// Catálogos estáticos
export const CATEGORIAS = ['Infantil', 'Juvenil', 'Adulto', 'Mayores'] as const;
export const DISCIPLINAS = [
  'Fútbol',
  'Natación',
  'Atletismo',
  'Ciclismo',
] as const;

export const ROLES = [
  { nombre: 'SUPER_ADMIN', descripcion: 'Acceso completo' },
  { nombre: 'ADMIN', descripcion: 'Gestión de usuarios y config' },
  { nombre: 'SECRETARIA', descripcion: 'Tareas administrativas' },
  { nombre: 'DTM_EIDE', descripcion: 'Dirección técnica' },
  { nombre: 'DTM', descripcion: 'Dirección técnica' },
  { nombre: 'PDA', descripcion: 'Apoyo actividades' },
  { nombre: 'FINANCIERO', descripcion: 'Gestión presupuestos' },
  { nombre: 'ENTRENADOR', descripcion: 'Entrenamiento atletas' },
] as const;

// Usuarios iniciales (referencian IDs 1/1; en seed se puede resolver por nombre si prefieres)
export const USUARIOS = [
  {
    nombre: 'Super',
    apellido: 'Admin',
    email: 'superadmin@ejemplo.com',
    cedula: '1234567890',
    rol: 'SUPER_ADMIN',
  },
  {
    nombre: 'Admin',
    apellido: 'Principal',
    email: 'admin@ejemplo.com',
    cedula: '1234567891',
    rol: 'ADMIN',
  },
  {
    nombre: 'Ana',
    apellido: 'Gómez',
    email: 'secretaria@ejemplo.com',
    cedula: '1234567892',
    rol: 'SECRETARIA',
  },
  {
    nombre: 'Carlos',
    apellido: 'López',
    email: 'dtm@ejemplo.com',
    cedula: '1234567893',
    rol: 'DTM_EIDE',
  },
  {
    nombre: 'María',
    apellido: 'Pérez',
    email: 'pda@ejemplo.com',
    cedula: '1234567894',
    rol: 'PDA',
  },
  {
    nombre: 'Juan',
    apellido: 'Martínez',
    email: 'financiero@ejemplo.com',
    cedula: '1234567895',
    rol: 'FINANCIERO',
  },
  {
    nombre: 'Luis',
    apellido: 'Rodríguez',
    email: 'entrenador@ejemplo.com',
    cedula: '1234567896',
    rol: 'ENTRENADOR',
  },
] as const;

// Eventos + ediciones (ejemplo mínimo). Agrega más filas según tu tabla.
// datos.ts (actualiza SOLO esta constante)
export const EVENTOS = [
  {
    codigo: 'EV-AJD-001',
    tipoParticipacion: 'PARTICIPACION',
    tipoEvento: 'CAMPEONATO',
    nombre: 'Campeonato Nacional Oficial Sub 16 Ajedrez',
    genero: 'AMBOS',
    disciplinaNombre: 'Atletismo',
    categoriaNombre: 'Juvenil',
    alcance: 'NACIONAL',
    // ↓ Campos planos (sin ediciones)
    lugar: 'Centro Deportivo',
    provincia: 'Pichincha',
    ciudad: 'Quito',
    pais: 'Ecuador',
    fechaInicio: '2025-03-12T09:00:00Z',
    fechaFin: '2025-03-16T18:00:00Z',
    numEntrenadoresHombres: 1,
    numEntrenadoresMujeres: 0,
    numAtletasHombres: 3,
    numAtletasMujeres: 3,
  },
  {
    codigo: 'EV-FUT-002',
    tipoParticipacion: 'ORGANIZACION',
    tipoEvento: 'TORNEO',
    nombre: 'Torneo Provincial de Fútbol Sub 18',
    genero: 'MASCULINO',
    disciplinaNombre: 'Fútbol',
    categoriaNombre: 'Juvenil',
    alcance: 'PROVINCIAL',
    lugar: 'Estadio Reina del Cisne',
    provincia: 'Loja',
    ciudad: 'Loja',
    pais: 'Ecuador',
    fechaInicio: '2025-06-01T09:00:00Z',
    fechaFin: '2025-06-10T18:00:00Z',
    numEntrenadoresHombres: 5,
    numEntrenadoresMujeres: 0,
    numAtletasHombres: 120,
    numAtletasMujeres: 0,
  },
  {
    codigo: 'EV-NAT-003',
    tipoParticipacion: 'PARTICIPACION',
    tipoEvento: 'CAMPEONATO',
    nombre: 'Campeonato Nacional de Natación',
    genero: 'AMBOS',
    disciplinaNombre: 'Natación',
    categoriaNombre: 'Adulto',
    alcance: 'NACIONAL',
    // Usamos la 1ra edición (Guayaquil)
    lugar: 'Piscina Olímpica',
    provincia: 'Guayas',
    ciudad: 'Guayaquil',
    pais: 'Ecuador',
    fechaInicio: '2025-07-15T09:00:00Z',
    fechaFin: '2025-07-20T18:00:00Z',
    numEntrenadoresHombres: 3,
    numEntrenadoresMujeres: 2,
    numAtletasHombres: 50,
    numAtletasMujeres: 40,
  },
  {
    codigo: 'EV-CIC-004',
    tipoParticipacion: 'PARTICIPACION',
    tipoEvento: 'CLASIFICATORIO',
    nombre: 'Clasificatorio Nacional de Ciclismo Ruta',
    genero: 'AMBOS',
    disciplinaNombre: 'Ciclismo',
    categoriaNombre: 'Mayores',
    alcance: 'NACIONAL',
    // Usamos la 1ra edición (Ambato)
    lugar: 'Ruta Andina',
    provincia: 'Tungurahua',
    ciudad: 'Ambato',
    pais: 'Ecuador',
    fechaInicio: '2025-09-01T07:00:00Z',
    fechaFin: '2025-09-05T17:00:00Z',
    numEntrenadoresHombres: 4,
    numEntrenadoresMujeres: 1,
    numAtletasHombres: 80,
    numAtletasMujeres: 20,
  },
  {
    codigo: 'EV-ATL-005',
    tipoParticipacion: 'ORGANIZACION',
    tipoEvento: 'TORNEO',
    nombre: 'Torneo Intercolegial de Atletismo',
    genero: 'AMBOS',
    disciplinaNombre: 'Atletismo',
    categoriaNombre: 'Infantil',
    alcance: 'CANTONAL',
    lugar: 'Coliseo Municipal',
    provincia: 'Loja',
    ciudad: 'Loja',
    pais: 'Ecuador',
    fechaInicio: '2025-05-01T09:00:00Z',
    fechaFin: '2025-05-03T18:00:00Z',
    numEntrenadoresHombres: 2,
    numEntrenadoresMujeres: 1,
    numAtletasHombres: 60,
    numAtletasMujeres: 40,
  },
] as const;
